### ISSUE TITLE
Sensor Question

### ISSUE THREAD

**Issue by DanRamage** [sdc53/RealDash-CAN-MQTT-Node-Red-2-way#1]
I realize this isn't an issue, but was curious about your sensor setup. Will you be running this in lieu of the current gauge setup, or running it in tandem? I've been wanting to do something similar with my old '63 Mercury wagon but wanted to run in tandem with what's there.

**Comment by sdc53** [comment]
Yeah, this isn't an issue.  Don't open issues for things that are already addressed in the docs.  This question is already answered in the schematic and video for the companion sensor project.  There is a relay that retains existing gauge operation. https://github.com/sdc53/ESPhome-engine-coolant-and-oil-pressure-sensor
